onyx-pkg-config: Check if the SYSROOT is not set
Should help prevent sneaky issues with builds and pkg-config

Signed-off-by: Pedro Falcato <pedro.falcato@gmail.com>

diff --git a/buildpkg/onyx-pkg-config b/buildpkg/onyx-pkg-config
--- a/buildpkg/onyx-pkg-config
+++ b/buildpkg/onyx-pkg-config
@@ -1,4 +1,10 @@
 #!/bin/sh
+
+if [ -z "$SYSROOT" ]; then
+    echo "Error: onyx-pkg-config: SYSROOT not set"
+    exit 1
+fi
+
 export PKG_CONFIG_SYSROOT_DIR=$SYSROOT
 export PKG_CONFIG_LIBDIR=$SYSROOT/usr/lib/pkgconfig
 
